feat: add metrics via values file
cpwc/aws-quota-checker pull request #1
Opened 2024-11-21 14:28 UTC by tipci

2024-11-21 14:43 UTC, cpwc requested changes

2024-11-21 14:43 UTC, cpwc commented on charts/aws-quota-checker/values.yaml
> +  - vpc_count,ec2_eip_count,vpc_nat_gateways_per_availability_zone
```suggestion
  - vpc_count,ec2_eip_count,vpc_nat_gateways_per_availability_zone
  
```

2024-11-21 14:43 UTC, cpwc approved these changes

2024-11-22 05:34 UTC, pbaderia01 approved these changes

2024-11-22 05:37 UTC, merged